# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_program_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_image_url', models.TextField()),
                ('abstract', models.TextField()),
                ('member_list', models.TextField()),
                ('advisor', models.TextField()),
                ('future_work', models.TextField()),
                ('topic', models.TextField()),
                ('title', models.TextField()),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_boards.DegreeProgram')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_year', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_boards.Year'),
        ),
    ]
