# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='class_year',
        ),
        migrations.AddField(
            model_name='year',
            name='year',
            field=models.CharField(default=2014, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='degreeprogram',
            name='degree_program_name',
            field=models.CharField(max_length=255),
        ),
    ]
