# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_boards', '0002_auto_20160222_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeprogram',
            name='degree_program_name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='degree_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_boards.DegreeProgram', to_field='degree_program_name'),
        ),
    ]
