# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_boards', '0003_auto_20160222_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_boards.Year', to_field='year'),
        ),
    ]
